# Generated by Django 2.2 on 2020-02-07 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainaccepted', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name_plural': 'Events'},
        ),
    ]
