# Generated by Django 2.2 on 2020-02-07 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainaccepted', '0002_auto_20200207_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='organization',
            new_name='organisation',
        ),
    ]
